### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by sn0rcha** [FutureMind/hug-sqlalchemy-template#1]
Hey There,

Thanks for the boilerplate!

I was wondering if it was possible to get you to post an example Model and route with model activity (fetching records etc).

**Comment by tomlaszczuk** [comment]
Hi. 
Yeah. I've put some simple examples on seperate branches. 

user_jwt_auth_example_project - It contains authentication example, user model and some basic endpoints.

I've updated readme about examples information
